# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'device_selector.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PwIODeviceSelector(object):
    def setupUi(self, PwIODeviceSelector):
        PwIODeviceSelector.setObjectName("PwIODeviceSelector")
        PwIODeviceSelector.resize(395, 304)
        self.horizontalLayout = QtWidgets.QHBoxLayout(PwIODeviceSelector)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listView = QtWidgets.QListView(PwIODeviceSelector)
        self.listView.setObjectName("listView")
        self.horizontalLayout.addWidget(self.listView)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(PwIODeviceSelector)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(PwIODeviceSelector)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.listView_2 = QtWidgets.QListView(PwIODeviceSelector)
        self.listView_2.setObjectName("listView_2")
        self.horizontalLayout.addWidget(self.listView_2)

        self.retranslateUi(PwIODeviceSelector)
        QtCore.QMetaObject.connectSlotsByName(PwIODeviceSelector)

    def retranslateUi(self, PwIODeviceSelector):
        _translate = QtCore.QCoreApplication.translate
        PwIODeviceSelector.setWindowTitle(_translate("PwIODeviceSelector", "GroupBox"))
        self.pushButton.setText(_translate("PwIODeviceSelector", "Add"))
        self.pushButton_2.setText(_translate("PwIODeviceSelector", "Remove"))
